DROP DATABASE LIVEDB;
CREATE DATABASE LIVEDB;
USE LIVEDB;
DROP TABLE PRODUCT1;
CREATE TABLE PRODUCT1 (
  PRODUCT_ID INT(5),
  PRODUCTNAME VARCHAR(50),
  PRICE FLOAT
);
SELECT * FROM PRODUCT1;

desc PRODUCT1;

-- modifying multiple columns
ALTER TABLE `PRODUCT1` 
MODIFY PRODUCT_ID INT(6),
MODIFY `PRODUCTNAME` VARCHAR(25) NOT NULL;

-- renaming columns
ALTER TABLE `PRODUCT1` 
CHANGE PRODUCT_ID PRODUCT_ID1 INT(6),
CHANGE `PRODUCTNAME` PRODUCTNAME1  VARCHAR(20)  NULL;
--CHANGE `PRODUCTNAME` PRODUCT_ID1  VARCHAR(25) NOT NULL;

-- ERROR BEACAUSE OF SIZE DIMENSION
ALTER TABLE `PRODUCT1` 
RENAME COLUMN PRODUCT_ID1 TO PRODUCT_ID2 INT(7),
RENAME COLUMN `PRODUCTNAME1` TO PRODUCTNAME2  VARCHAR(30);

-- SYNTAX 2
ALTER TABLE `PRODUCT1` 
RENAME COLUMN PRODUCT_ID1 TO PRODUCT_ID2,
RENAME COLUMN `PRODUCTNAME1` TO PRODUCTNAME2;

-- RENAME TABLES 
ALTER TABLE PRODUCT1 RENAME PRODUCT2;
RENAME TABLE PRODUCT2 TO PRODUCT3;
DESC PRODUCT1;
DESC PRODUCT2;
DESC PRODUCT3;
SELECT * FROM PRODUCT3;


---------TRANSACTIONS-----------------

DROP TABLE PRODUCT1;
CREATE TABLE PRODUCT1 (
  PRODUCT_ID INT(5),
  PRODUCTNAME VARCHAR(50),
  PRICE FLOAT
);
SELECT * FROM PRODUCT1;
-- BY DEFAULT MySQL automatically commits the changes permanently to the database
-- DISABLING AUTOCOMMIT
SET autocommit = 0;
SET autocommit = OFF
SET autocommit = on
--  enable the autocommit mode explicitly
SET autocommit = 1;
SELECT @@AUTOCOMMIT;


INSERT INTO PRODUCT1 VALUES   (1, 'BARBIQUE', 50.5);
SELECT * FROM PRODUCT1;

START TRANSACTION;
INSERT INTO `PRODUCT1` VALUES   (2, 'BARBIE', 50.5);
SELECT * FROM PRODUCT1;
COMMIT;

START TRANSACTION;
INSERT INTO `PRODUCT1` VALUES   (3, 'DOLLY', 50.5);
SELECT * FROM PRODUCT1;
ROLLBACK;
------------------  XTRA ------------------------
INSERT INTO `PRODUCT1` VALUES   (1, 'BARBIE', 50.5);
SELECT * FROM PRODUCT1;


-- PLACEHOLDER
-- USER DEFINED VARIABLE
  SET @PRODUCT_ID = 1;
  SELECT @PRODUCT_ID;
select * from PRODUCT1 where PRODUCT_ID = @PRODUCT_ID;


 SET @VPRODUCT_ID = 2;
 SET @VPRODUCTNAME = 'BOSEREVIVE';
 SET @VPRICE = 5.5;
INSERT INTO `PRODUCT1` VALUES   (@VPRODUCT_ID, @VPRODUCTNAME, @VPRICE);
SELECT * FROM PRODUCT1;

-- CLEAR SCREEN 
SYSTEM CLS;